import Head from "next/head";
import LandingPage from "../../components/landingPage";
import axios from "axios";
import { GET_ALLOWED_DESKTOP_GAMES, GET_GAMES_PROVIDERS } from "@/endpoints";
import { useContext, useEffect } from "react";
import { DataContext } from "../../context/DataContext";
// import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export default function Home({ allowedGames, gamesProvider }) {
  const { setProviders, setAllowedGames } = useContext(DataContext);
  useEffect(() => {
    setProviders(gamesProvider);
  }, [gamesProvider]);

  useEffect(() => {
    setAllowedGames(allowedGames);
  }, [allowedGames]);

  return (
    <>
      <Head>
        <title>Betpool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
    </>
  );
}
export async function getStaticProps({ locale }) {
  const allowedGamesData = await axios.get(GET_ALLOWED_DESKTOP_GAMES, {
    headers: {
      Accept: "application/vnd.softswiss.v1+json",
    },
  });
  const allowedGames = allowedGamesData.data;

  const gamesProvidersData = await axios.get(GET_GAMES_PROVIDERS, {
    headers: {
      Accept: "application/vnd.softswiss.v1+json",
    },
  });
  const gamesProvider = gamesProvidersData.data;

  return {
    props: {
      // ...(await serverSideTranslations(locale, ["translations"])),
      allowedGames,
      gamesProvider,
    },
  };
}
